name: cached
description: Dart package with build-in code generation. Simplifies and speedup creation of cache mechanism for dart classes.
version: 1.7.0
repository: https://github.com/Iteo/cached
issue_tracker: https://github.com/Iteo/cached/issues
homepage: https://github.com/Iteo/cached
documentation: https://github.com/Iteo/cached/blob/master/packages/cached/README.md
topics:
  - cache
  - lru
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  analyzer: ^6.2.0
  build: ^2.3.0
  cached_annotation: ^1.7.0
  collection: ^1.16.0
  meta: ^1.7.0
  source_gen: ">=1.2.2 <3.0.0"
  source_helper: ^1.3.2

dev_dependencies:
  async: ^2.9.0
  build_runner: ^2.4.6
  path: ^1.8.2
  source_gen_test: ^1.0.3
  test: ^1.21.1
  linteo: ^1.0.1

screenshots:
  - description: The cached package logo.
    path: cached_sygnet.png
